### ISSUE TITLE
Error with the 3D model in the case there are no exclusion region provided

### ISSUE THREAD

**Issue by mdebony** [mdebony/acceptance_modelisation#32]
When you only provide an empty list of exclusion regions for a 3D model, an error is raised.

The full stack trace :
```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/cProfile.py", line 191, in <module>
    main()
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/cProfile.py", line 180, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/cProfile.py", line 20, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/profile.py", line 63, in runctx
    prof.runctx(statement, globals, locals)
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/cProfile.py", line 101, in runctx
    exec(cmd, globals, locals)
  File "Test3DFull_HESS.py", line 25, in <module>
    a = acceptance_creator.create_acceptance_map_per_observation(obs_collection, zenith_binning=True, zenith_interpolation=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/base_acceptance_map_creator.py", line 981, in create_acceptance_map_per_observation
    acceptance_map = self.create_acceptance_map_cos_zenith_interpolated(observations=observations,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/base_acceptance_map_creator.py", line 902, in create_acceptance_map_cos_zenith_interpolated
    dict_binned_model = base_model or self.create_model_cos_zenith_binned(off_observations)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/base_acceptance_map_creator.py", line 636, in create_model_cos_zenith_binned
    binned_model = [self.create_acceptance_map(binned_obs) for binned_obs in binned_observations]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/base_acceptance_map_creator.py", line 636, in <listcomp>
    binned_model = [self.create_acceptance_map(binned_obs) for binned_obs in binned_observations]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/grid3d_acceptance_map_creator.py", line 210, in create_acceptance_map
    count_map_background, exp_map_background, exp_map_background_total, livetime = self._create_base_computation_map(
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/post_doc_cea/bkgmodel/test_dev/acceptance_modelisation/base_acceptance_map_creator.py", line 370, in _create_base_computation_map
    mask = geom.contains(obs.events.radec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/md274436/software/miniforge3/envs/gammapy-analysis/lib/python3.11/site-packages/gammapy/maps/region/geom.py", line 236, in contains
    raise ValueError("Region definition required.")```

**Comment by mdebony** [comment]
Closes by PR #35
